### PR TITLE
Add tracer and formatter for sending traces to zipkin query HTTP api.

### PR DESCRIPTION
**Pull request by sydcanem**
Fixes issue #39

### CODE REVIEW

**Comment by mduleone** [comment]
Once this is merged in and implemented in the npm release, this will be really useful for us. Please review and merge asap :)

**Comment by dustyburwell** [comment]
This seems fine, and almost entirely additive. I'm inclined to merge. @cyli?

**Comment by cyli** [comment]
👍

**Comment by sydcanem** [comment]
Thanks @cyli

**Comment by cyli** [comment]
@sydcanem Thank you for your contribution!  A new version has been published to NPM

**Pull request merged**
